name: Create an image (Fast)
description: Generate an image from text quickly with Flux Schnell.
tip: Flux is a text to image model that excels at prompt coherence and text generation. This should always be the default way to generate an image from text!
output_type: image
cost_estimate: 1 * n_samples
handler: comfyui
base_model: flux-schnell
resolutions: [21-9_1536x640, 16-9_1344x768, 3-2_1216x832, 4-3_1152x896, 1-1_1024x1024, 3-4_896x1152, 2-3_832x1216, 9x16_1152x2048, 9-21_640x1536]
comfyui_output_node_id: 9
parameters:
- name: prompt
  label: Prompt
  description: Text prompt
  tip: Flux loves very detailed and descriptive prompts so try to be elaborate. Flux is also great at drawing text in images so feel free to add something if it makes sense.
  type: string
  required: true
  default:  
  comfyui: 
    node_id: 6
    field: inputs
    subfield: text
- name: width
  label: Width
  description: Width in pixels
  type: int
  required: true
  default: 1024
  minimum: 256
  maximum: 2048
  step: 8
  comfyui: 
    node_id: 5
    field: inputs
    subfield: width
- name: height
  label: Height
  description: Height in pixels
  type: int
  required: true
  default: 1024
  minimum: 256
  maximum: 2048
  step: 8
  comfyui: 
    node_id: 5
    field: inputs
    subfield: height
- name: seed
  label: Seed
  description: Set random seed for reproducibility. If blank, will be set to a random value.
  tip: You should only set this if you want to start from/copy the seed of a previous image. Unless one is specified, you should leave this blank! 
  type: int
  default: random
  minimum: 0
  maximum: 2147483647
  comfyui: 
    node_id: 25
    field: inputs
    subfield: noise_seed
- name: n_samples
  label: Number of samples
  description: Number of samples to generate
  tip: This is the number of tries to generate for the prompt. If you get a request for n_samples > 1, you are still using a *single* prompt for the whole set.
  type: int
  default: 1
  minimum: 1
  maximum: 4
